-- liquibase formatted sql

-- changeset ivan.rudik:base

CREATE TABLE PRODUCT (
    ID IDENTITY,
    NAME VARCHAR(50),
    COUNT INT
);

CREATE TABLE MONEY (
    ID IDENTITY,
    NAME VARCHAR(50),
    COUNT INT,
    DESCRIPTION VARCHAR(250),
    WORTH DECIMAL
);

CREATE TABLE SNACK_ORDER (
    ID IDENTITY,
    ORDERPOSITIONS INT,
    MONEYPOSITIONS INT
);

CREATE TABLE MONEYPOSITION (
    ID IDENTITY,
    COUNT INT,
    ORDER_ID INT,
    FOREIGN KEY (ORDER_ID) REFERENCES SNACK_ORDER (ID)
);

CREATE TABLE ORDERPOSITION (
    ID IDENTITY,
    COUNT INT,
    ORDER_ID INT,
    FOREIGN KEY (ORDER_ID) REFERENCES SNACK_ORDER (ID)
);