-- liquibase formatted sql

-- changeset ivan.rudik:base

CREATE TABLE PRODUCT (
    ID IDENTITY,
    NAME VARCHAR(50),
    COUNT INT,
    PREIS DECIMAL
);

CREATE TABLE MONEY (
    ID IDENTITY,
    NAME VARCHAR(50),
    COUNT INT,
    DESCRIPTION VARCHAR(250),
    WORTH DECIMAL
);

CREATE TABLE SNACK_ORDER (
    ID IDENTITY,
    ORDERPOSITIONS INT,
    MONEYPOSITIONS INT,
    STATUS VARCHAR(10)
);

CREATE TABLE MONEYPOSITION (
    ID IDENTITY,
    COUNT INT,
    ORDER_ID INT,
    MONEY_ID INT,
    FOREIGN KEY (ORDER_ID) REFERENCES SNACK_ORDER (ID),
    FOREIGN KEY (MONEY_ID) REFERENCES MONEY (ID)
);

CREATE TABLE ORDERPOSITION (
    ID IDENTITY,
    COUNT INT,
    ORDER_ID INT,
    PRODUCT_ID INT,
    FOREIGN KEY (ORDER_ID) REFERENCES SNACK_ORDER (ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);